<Workspace Version="1.3.0.875" X="78.1477304338372" Y="271.243575282373" zoom="0.415909810048132" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="List.List" resolvedName="List.List" assemblyName="Archi-lab_Grimshaw.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="82d0d209-e195-4c5a-afde-e85094e27465" type="PythonNodeModels.PythonNode" nickname="Python Script" x="511.717957882596" y="233.521632749631" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import Autodesk
import System

from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
sheetnames = IN[0]
sheetNumber = IN[1]
titleblock = UnwrapElement(IN[2])
sheetlist = list()

TransactionManager.Instance.EnsureInTransaction(doc)

for number in range(len(sheetNumber)):
    newsheet = ViewSheet.Create(doc, titleblock.Id)
    newsheet.Name = sheetnames[number]
    newsheet.SheetNumber = sheetNumber[number]
    sheetlist.append(newsheet.ToDSType(False))

TransactionManager.Instance.TransactionTaskDone()
OUT = sheetlist</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Watch guid="f3c9eff3-e77f-464a-8f2b-e0470d19e01c" type="CoreNodeModels.Watch" nickname="Watch" x="654.176722310373" y="234.952207300908" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <DSRevitNodesUI.FamilyTypes guid="97f0093c-8fbf-4638-80ba-f99ad7bff1c8" type="DSRevitNodesUI.FamilyTypes" nickname="Family Types" x="162.349720328143" y="358.92868841531" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="1125:Titleblock E - Standard:SOM-E-Vertical" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="0fd9edf5-7d46-4960-8fe0-621bbd3dd246" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.FirstItem" x="253.459380720173" y="251.097928340369" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.FirstItem@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="33b9b8fe-604c-4062-a793-0b98e48a6ac8" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.LastItem" x="255.494709320277" y="127.165265169561" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.LastItem@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="0b50e6c9-c92e-4c2d-9c01-2d25999a2f85" type="PythonNodeModels.PythonNode" nickname="Python Script" x="50.829946279337" y="184.804418824538" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

clr.AddReference('Microsoft.Office.Interop.Excel, Version=11.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c')
from Microsoft.Office.Interop import Excel
from System.Runtime.InteropServices import Marshal

path = IN[0]
ex = Excel.ApplicationClass()
ex.Visible = False;
ex.DisplayAlerts = False

workbook = ex.Workbooks.Open(path)
ws = workbook.Worksheets[1]
x1range = ws.Range["A1", "A4"]
x2range = ws.Range["B1", "B4"]

r1 = x1range.Value2
r2 = x2range.Value2

OUT = r1, r2

ex.ActiveWorkbook.Close(False)
Marshal.ReleaseComObject(ws)
Marshal.ReleaseComObject(workbook)
Marshal.ReleaseComObject(ex)</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Watch guid="cb4fb8fd-b306-4d44-b055-f86b4201a1d7" type="CoreNodeModels.Watch" nickname="Watch" x="232.514931839967" y="-190.861361732299" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <CoreNodeModels.Input.Filename guid="4b629c38-6e63-4d23-80f5-fbb0eed25881" type="CoreNodeModels.Input.Filename" nickname="File Path" x="-93.946077087663" y="183.12636588688" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>.\Sheets.xlsx</System.String>
      <HintPath>F:\00-PROGRAMING - DYNAMO\pyDynamo\pyTest\Sheets.xlsx</HintPath>
    </CoreNodeModels.Input.Filename>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="82d0d209-e195-4c5a-afde-e85094e27465" start_index="0" end="f3c9eff3-e77f-464a-8f2b-e0470d19e01c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="97f0093c-8fbf-4638-80ba-f99ad7bff1c8" start_index="0" end="82d0d209-e195-4c5a-afde-e85094e27465" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0fd9edf5-7d46-4960-8fe0-621bbd3dd246" start_index="0" end="82d0d209-e195-4c5a-afde-e85094e27465" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="33b9b8fe-604c-4062-a793-0b98e48a6ac8" start_index="0" end="82d0d209-e195-4c5a-afde-e85094e27465" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0b50e6c9-c92e-4c2d-9c01-2d25999a2f85" start_index="0" end="cb4fb8fd-b306-4d44-b055-f86b4201a1d7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0b50e6c9-c92e-4c2d-9c01-2d25999a2f85" start_index="0" end="0fd9edf5-7d46-4960-8fe0-621bbd3dd246" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0b50e6c9-c92e-4c2d-9c01-2d25999a2f85" start_index="0" end="33b9b8fe-604c-4062-a793-0b98e48a6ac8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4b629c38-6e63-4d23-80f5-fbb0eed25881" start_index="0" end="0b50e6c9-c92e-4c2d-9c01-2d25999a2f85" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>