<Workspace Version="1.3.0.875" X="-615.94356805468" Y="-277.669396249697" zoom="0.981677155098297" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <DSRevitNodesUI.Categories guid="e1aede38-2998-4737-8cbe-340ac7b3f112" type="DSRevitNodesUI.Categories" nickname="Categories" x="658" y="394.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="194:Floors" />
    <DSRevitNodesUI.ElementsOfCategory guid="cfc2144f-a714-4a78-b8d1-f09eb32ffeab" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="875" y="394.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <CoreNodeModels.Watch guid="7a5538eb-0f9f-4dbb-aec0-f3a2dcfdbc3e" type="CoreNodeModels.Watch" nickname="Watch" x="1246.57723834553" y="398.01104210611" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <PythonNodeModels.PythonNode guid="60268d52-0e75-4ef6-8d75-5f787dbcd179" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1082.23760280049" y="394.923624193624" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument

elements = UnwrapElement(IN[0])

OUTList = []
OUTElements = []

for e in elements:
	x = e.LookupParameter('Workset')
	if x.AsValueString() == 'STRUC':
		OUTList.append(x.AsValueString())
  		OUTElements.append(e)
		
   

OUT = OUTList, OUTElements</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="e1aede38-2998-4737-8cbe-340ac7b3f112" start_index="0" end="cfc2144f-a714-4a78-b8d1-f09eb32ffeab" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cfc2144f-a714-4a78-b8d1-f09eb32ffeab" start_index="0" end="60268d52-0e75-4ef6-8d75-5f787dbcd179" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="60268d52-0e75-4ef6-8d75-5f787dbcd179" start_index="0" end="7a5538eb-0f9f-4dbb-aec0-f3a2dcfdbc3e" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>